# Generated by Django 4.2.30 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gmail', 'Gmail'), ('instagram', 'Instagram')], max_length=20)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('spam_score', models.IntegerField(default=0)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_phishing', models.BooleanField(default=False)),
                ('should_notify', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
            ],
        ),
    ]
