# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-received_at'], name='analyzer_me_receive_71ac34_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source'], name='analyzer_me_source_c1fcba_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['category'], name='analyzer_me_categor_602b9e_idx'),
        ),
    ]
