# Generated by Django 4.2.30 on 2026-04-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_message_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='analyzer_me_receive_087696_idx',
            old_name='analyzer_me_receive_71ac34_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='analyzer_me_source_c74763_idx',
            old_name='analyzer_me_source_c1fcba_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='analyzer_me_categor_f2cdd6_idx',
            old_name='analyzer_me_categor_602b9e_idx',
        ),
    ]
