# Generated by Django 4.2.30 on 2026-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_rename_analyzer_me_receive_71ac34_idx_analyzer_me_receive_087696_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('gmail', 'Gmail'), ('instagram', 'Instagram')], default='instagram', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
