# Generated by Django 4.2.30 on 2026-04-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_favouriteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredWhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(help_text='WhatsApp group JID e.g. 120363xxx@g.us', max_length=100, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='favouriteuser',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], default='instagram', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remind_at', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='analyzer.message')),
            ],
            options={
                'indexes': [models.Index(fields=['remind_at', 'is_sent'], name='analyzer_re_remind__e1bea0_idx')],
            },
        ),
    ]
