# Generated by Django 4.2.30 on 2026-04-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_monitoredwhatsappgroup_alter_favouriteuser_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='urls_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='source',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20),
        ),
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('is_safe', models.BooleanField(default=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_scans', to='analyzer.message')),
            ],
            options={
                'indexes': [models.Index(fields=['is_safe'], name='analyzer_ur_is_safe_b752d4_idx')],
            },
        ),
    ]
