# Generated by Django 4.2.30 on 2026-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_message_urls_scanned_reminder_source_urlscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_reply_draft',
            field=models.TextField(blank=True, help_text='AI-pre-generated draft for this message', null=True),
        ),
    ]
