# Generated by Django 4.2.30 on 2026-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_message_ai_reply_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auto_replied',
            field=models.BooleanField(default=False, help_text='Whether an automated reply was sent for this message'),
        ),
    ]
