# Generated by Django 4.2.30 on 2026-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_message_auto_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_external_id',
            field=models.CharField(blank=True, help_text='Platform-specific ID (IG PK or WA JID)', max_length=255, null=True),
        ),
    ]
